language: python
python:
  - "3.6"
before_install:
    # install essentia

install:
  - pip install -r requirements.txt

script: pytest test/EvalMetricsTest.py --cov-report term-missing --cov app -v
branches:
  only:
    - master